version: "3.7"
services:
  pg:
    image: postgis/postgis:15-3.5
    restart: always
    environment:
      POSTGRES_USER: dev-user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dev_db
    ports:
      - 5432:5432
    expose:
      - "5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build:
      context: .
    container_name: backend
    env_file:
      - .env
    ports:
      - 8000:8000
    entrypoint: ./scripts/run.sh
    depends_on:
      - pg

volumes:
  db-data:
