"""initial

Revision ID: 5fbd82629c7f
Revises:
Create Date: 2025-08-18 19:36:55.077842

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5fbd82629c7f"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "building",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("address", sa.String(), nullable=False),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("long", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("pk"),
    )
    op.create_table(
        "operation_type",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("parent_type_pk", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_type_pk"],
            ["operation_type.pk"],
        ),
        sa.PrimaryKeyConstraint("pk"),
    )
    op.create_table(
        "organization",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("building_pk", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["building_pk"],
            ["building.pk"],
        ),
        sa.PrimaryKeyConstraint("pk"),
    )
    op.create_table(
        "organization_to_operation_type",
        sa.Column("organization_pk", sa.Integer(), nullable=False),
        sa.Column("operation_type_pk", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["operation_type_pk"],
            ["operation_type.pk"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_pk"],
            ["organization.pk"],
        ),
        sa.PrimaryKeyConstraint("organization_pk", "operation_type_pk"),
    )
    op.create_table(
        "phone_number",
        sa.Column("pk", sa.Integer(), nullable=False),
        sa.Column("number", sa.String(), nullable=False),
        sa.Column("organization_pk", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_pk"],
            ["organization.pk"],
        ),
        sa.PrimaryKeyConstraint("pk"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("phone_number")
    op.drop_table("organization_to_operation_type")
    op.drop_table("organization")
    op.drop_table("operation_type")
    op.drop_table("building")
    # ### end Alembic commands ###
